import React from 'react';
import Particles from 'react-particles-js';
import { BrowserRouter as Router, Route, Link } from "react-router-dom";
import './App.css';



function Index() {
  return <h2>Home</h2>;
}

function Privacy() {
  return (
  <div style={{color: 'white'}}>
  <h2>Privacy Policy</h2>
  
  <p>Your privacy is important to us. It is Alexander Motch's policy to respect your privacy regarding any information we may collect from you through our games.</p>
  <p>We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.</p>
  <p>We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorised access, disclosure, copying, use or modification.</p>
  <p>We don’t share any personally identifying information publicly or with any undisclosed third-parties, except when required to by law.</p>
  <p>Our games link to external services that are not operated by us. Please be aware that we have no control over the content and practices of these services, and cannot accept responsibility or liability for their respective privacy policies.</p>
  <p>You are free to refuse our request for your personal information. You are also free to examine or have destroyed any information collected on you, with the understanding that we may be unable to provide you with some of your desired services.</p>
  <p>Your continued use of our games will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.</p>
  <p>This policy is effective as of 14 July 2019.</p>
  <p>Generated by <a title="Privacy Policy Template Generator" href="https://getterms.io/">GetTerms.io</a></p>
  </div>);
}

function Users() {
  return <h2>Users</h2>;
}

function App() {
  return (
   
    <Router>
       
                
      <div id="particles">
      <Particles
                params={{
                    "particles": {
                        "line_linked": {
                                    "color":"#FFFFFF"
                                    },

                                    "number": {
                                      "value": 10,
                                      "density": {
                                        "enable": false,
                                        "value_area": 800
                                      }
                                    },
                        "size": {
                            "value": 1
                        },
                        "move": {
                          "enable": true,
                          "speed": 12,
                          "direction": "none",
                          "random": false,
                          "straight": false,
                          "out_mode": "out",
                          "bounce": true,
                          "attract": {
                            "enable": true,
                            "rotateX": 600,
                            "rotateY": 1200
                          }
                        },
                        "polygon": {
                          "nb_sides": 2
                        },
                    },
                    
                    "interactivity": {
                      "detect_on": "canvas",
                      "events": {
                        "onhover": {
                          "enable": true,
                          "mode": ["repulse", "bubble"]
                        },
                        "onclick": {
                          "enable": false,
                          "mode": "push"
                        },
                        "resize": true
                      },
                      "modes": {
                        "grab": {
                          "distance": 800,
                          "line_linked": {
                            "opacity": 0
                          }
                        },
                        "bubble": {
                          "distance": 400,
                          "size": 5,
                          "duration": 5,
                          "opacity": 0.5,
                          "speed": 3,
                          "line_linked": {
                            "opacity": 0
                          }
                        },
                        "repulse": {
                          "distance": 10,
                          "duration": 0.2,
                          "line_linked": {
                            "opacity": 0
                          }
                        },
                        "push": {
                          "particles_nb": 4
                        },
                        "remove": {
                          "particles_nb": 2
                        }
                      }
                    }
                }}
                style={{
                        width: '100%',
                        background: `#000000` 
                 }}
                >

                  </Particles>
        <nav>
                 <div  className="spacing">
              <Link to="/" className="MenuLink">Home</Link>
              </div>
              <div  className="spacing">
              <Link to="/Privacy/" className="MenuLink">Privacy</Link>
              </div>
              <div  className="spacing">
              <Link to="/users/" className="MenuLink">Users</Link>
              </div>
        </nav>

        <Route path="/" exact component={Index} />
        <Route path="/Privacy" component={Privacy} />
        <Route path="/users/" component={Users} />
      

      </div>
      
    </Router>
  );
}


export default App;



